#!/usr/bin/env bash

# Common packages I usually have to install on Ubuntu

sudo apt-get update
sudo apt-get install -y --no-install-recommends \
  build-essential \
  curl \
  docker \
  git \
  htop \
  mesa-utils \
  ncdu \
  tmux \
  vim \
  zsh
