#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install -y --no-install-recommends \
  build-essential \
  curl \
  docker \
  git \
  gnupg \
  htop \
  mesa-utils \
  ncdu \
  tmux \
  vim \
  zsh

curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
sudo apt-get update && sudo apt-get install -y --no-install-recommends bazel
