" Editing
set autoindent
set smartindent
set expandtab
set shiftwidth=2
set tabstop=2 softtabstop=2
set smarttab
set nowrap
set list
set listchars=tab:··,trail:·,nbsp:⎵
set clipboard=unnamedplus

" Search
set hlsearch
set incsearch
set ignorecase
set smartcase
let mapleader=" "
nnoremap <CR> :noh<CR><CR> " Hit return to remove highlight after search
nnoremap <C-p> :Files<CR>
nnoremap <leader>p :Buffers<CR>

" Misc
set noerrorbells
set novisualbell
set nobackup
set noswapfile
set laststatus=2
set noshowmode

" File browsing
nnoremap <leader>n :NERDTreeFocus<CR>
nnoremap <C-t> :NERDTreeToggle<CR>

" Linelight options
let g:lightline = {
      \ 'colorscheme': 'onehalfdark',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'FugitiveHead'
      \ },
      \ }

" Syntax and colors
syntax on
set number
set ruler
set cursorline
set t_Co=256

set runtimepath+=~/.vim/pack/remote/start/onehalf/vim

try
  colorscheme onehalfdark
  highlight Normal guibg=NONE ctermbg=NONE
catch
  colorscheme default
  set background=dark
endtry

if exists('+termguicolors')
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif
