" Editing
set autoindent
set smartindent
set expandtab
set shiftwidth=2
set tabstop=2 softtabstop=2
set smarttab
set nowrap

" Search
set hlsearch
set incsearch
set ignorecase
set smartcase
nnoremap <CR> :noh<CR><CR> " Hit return to remove highlight after search

" Misc
set noerrorbells
set novisualbell
set nobackup
set noswapfile
set laststatus=2
set noshowmode

" File browsing 
let g:netrw_banner = 0
let g:netrw_browse_split = 4 " Open file in previous window 
let g:netrw_winsize = 25
let g:netrw_liststyle = 3
let g:netrw_altv = 1

" Linelight options
let g:lightline = {
      \ 'colorscheme': 'onehalfdark',
      \ 'active': {
      \   'left': [ [ 'mode', 'paste' ],
      \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
      \ },
      \ 'component_function': {
      \   'gitbranch': 'FugitiveHead'
      \ },
      \ }

" Plugins
call plug#begin('~/.vim/plugged')

Plug 'git@github.com:tpope/vim-fugitive.git'
Plug 'git@github.com:Valloric/YouCompleteMe.git', { 'do': './install.py' }
Plug 'git@github.com:preservim/nerdtree.git'
Plug 'git@github.com:sonph/onehalf.git', { 'rtp': 'vim' }
Plug 'git@github.com:itchyny/lightline.vim'

call plug#end()

autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif

" Syntax and colors
syntax on
set number
set ruler
set cursorline
set colorcolumn=80
set t_Co=256
colorscheme onehalfdark
highlight ColorColumn ctermbg=0 guibg=lightgrey 
highlight Normal guibg=NONE ctermbg=NONE
