" Syntax and colors
syntax on
colorscheme molokai
highlight ColorColumn ctermbg=0 guibg=lightgrey 
set number
set ruler
set cursorline
set showmatch
set colorcolumn=80

" Editing
set autoindent
set smartindent
set expandtab
set shiftwidth=2
set tabstop=2 softtabstop=2
set smarttab
set nowrap

" Search
set hlsearch
set incsearch
set ignorecase
set smartcase
nnoremap <CR> :noh<CR><CR> " Hit return remove highlight after search

" Misc
set noerrorbells
set novisualbell
set nobackup
set noswapfile
set laststatus=2

" Plugins
let vim_plug_file = '~/.vim/autoload/plug.vim'
let vim_plug_repo = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

if empty(glob(vim_plug_file))
  silent execute '!curl -fLo '.vim_plug_file.' --create-dirs '.vim_plug_repo
endif

call plug#begin('~/.vim/plugged')

Plug 'git@github.com:tpope/vim-fugitive'
Plug 'git@github.com:Valloric/YouCompleteMe.git', { 'do': './install.py' }

call plug#end()

autocmd VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
  \| PlugInstall --sync | source $MYVIMRC
\| endif
