#!/usr/bin/env bash

# Common packages I usually have to install on Ubuntu

sudo apt-get update
sudo apt-get install -y --no-install-recommends \
  build-essential \
  curl \
  cmake \
  docker \
  git \
  htop \
  mesa-utils \
  ncdu \
  python3 \
  python3-dev \
  python3-venv \
  tmux \
  vim \
  vim-gtk3 \
  zsh

