#!/usr/bin/env bash

# Common packages I usually have to install on Ubuntu
sudo apt-get update
sudo apt-get install -y --no-install-recommends \
  build-essential \
  curl \
  cmake \
  docker \
  git \
  htop \
  mesa-utils \
  ncdu \
  python3 \
  python3-dev \
  python3-venv \
  tmux \
  vim \
  vim-gtk3 \
  zsh

# Install vscode
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
rm -f packages.microsoft.gpg

sudo apt-get install apt-transport-https
sudo apt-get update
sudo apt-get install code
