#!/usr/bin/env bash

# Add source
wget -qO - https://hub.unity3d.com/linux/keys/public | sudo apt-key add -
echo "deb https://hub.unity3d.com/linux/repos/deb stable main" | sudo tee /etc/apt/sources.list.d/unityhub.list

# Install
sudo apt-get update
sudo apt-get install -y --no-install-recommends unityhub
